const BASE_URL = import.meta.env.BASE_URL || '/';

export interface RecipeIndexItem {
  id: string;
  title: string;
  slug: string;
  short_description: string;
  image: string;
  prepTime: number;
  servings: string;
  difficulty: "Easy" | "Medium" | "Advanced";
  cuisine: string;
  course: "Breakfast" | "Main" | "Dessert" | "Salad & Side" | "Bread" | "Sauce";
  tags: string[];
  keywords?: string[];
  featured: boolean;
  rating?: number;
  date_published: string;
}

const recipesData: RecipeIndexItem[] = [
  {
    id: "1",
    title: "Mehcheh Coussa",
    slug: "mehcheh-coussa",
    short_description: "Stuffed zucchinis cooked in tomato sauce.",
    image: `${BASE_URL}images/recipes/mehche_coussa.jpg`,
    prepTime: 30,
    servings: "4",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["coussa", "mehche", "zucchinis"],
    keywords: ["كوسة"],
    featured: true,
    rating: 4.8,
    date_published: "2025-05-31"
  },
  {
    id: "2",
    title: "Sayyadiyeh",
    slug: "sayyadiyeh",
    short_description: "Perfectly cooked white fish with marinated rice.",
    image: `${BASE_URL}images/recipes/sayyadiyeh.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Advanced",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["seafood", "healthy", "fish"],
    keywords: ["صيادية"],
    featured: true,
    rating: 4.9,
    date_published: "2025-10-10"
  },
  {
    id: "3",
    title: "Cooked Artichokes",
    slug: "cooked-artichokes",
    short_description: "Cooked artichokes Lebanese mezze",
    image: `${BASE_URL}images/recipes/cooked_artichokes.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["artichokes", "mezze", "side"],
    keywords: [],
    featured: true,
    rating: 5.0,
    date_published: "2020-05-06"
  },
  {
    id: "4",
    title: "Roast Beef",
    slug: "roast-beef",
    short_description: "Garlic-studded roast beef with green beans, mash, and silky pan gravy.",
    image: `${BASE_URL}images/recipes/Roast_beef.jpg`,
    prepTime: 20,
    servings: "4",
    difficulty: "Advanced",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["main", "roast beef"],
    keywords: [],
    featured: true,
    rating: 4.7,
    date_published: "2020-04-25"
  },
  {
    id: "5",
    title: "Chocolate & Red Berries Cupcakes",
    slug: "chocoalte-and-red-berries-cupcakes",
    short_description: "Rich chocolate cupcakes with fresh red berries.",
    image: `${BASE_URL}images/recipes/Chocolate_and_red_berries_cupcakes.jpg`,
    prepTime: 30,
    servings: "12",
    difficulty: "Easy",
    cuisine: "European",
    course: "Dessert",
    tags: ["chocolate", "berries", "cupcakes"],
    keywords: [],
    featured: true,
    rating: 4.9,
    date_published: "2020-05-02"
  },
  {
    id: "6",
    title: "Small Fluffy Japanese Milk Buns (Tangzhong)",
    slug: "small-fluffy-japanese-milk-buns",
    short_description: "Fluffy Japanese milk buns (tangzhong)—pillowy, lightly sweet, golden and soft.",
    image: `${BASE_URL}images/recipes/small_japanese_pain_au_lait.jpg`,
    prepTime: 15,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Japanese",
    course: "Breakfast",
    tags: ["breakfast", "japanese", "bread"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2020-04-15"
  },
  {
    id: "7",
    title: "Loubiyeh bi Zeit",
    slug: "loubiyeh-bi-zeit",
    short_description: "Lebanese green beans cooked in olive oil and tomatoes.",
    image: `${BASE_URL}images/recipes/Loubiyeh_bi_zeit.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["vegan", "healthy", "beans"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2020-05-15"
  },
  {
    id: "8",
    title: "Kebbit Batata",
    slug: "kebbit-batata",
    short_description: "Lebanese potato kibbeh with meat filling.",
    image: `${BASE_URL}images/recipes/kebbit_batata.jpg`,
    prepTime: 45,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["potato", "kibbeh", "traditional"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2020-06-01"
  },
  {
    id: "9",
    title: "Maple Glazed Walnut & Sugar Bun",
    slug: "maple-glazed-walnut-and-sugar-bun",
    short_description: "Maple-glazed walnut cinnamon bun—buttery, nutty, and beautifully swirled.",
    image: `${BASE_URL}images/recipes/maple_glazed_walnut_and_sugar_bun.jpg`,
    prepTime: 5,
    servings: "8",
    difficulty: "Medium",
    cuisine: "European",
    course: "Dessert",
    tags: ["dessert", "cinnamon bun", "sweet"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2021-04-09"
  },
  {
    id: "10",
    title: "Pear & Ricotta Tart",
    slug: "pear-and-ricotta-tart",
    short_description: "Flaky filo tart with ricotta, pears, and a touch of brown sugar.",
    image: `${BASE_URL}images/recipes/pear_and_ricotta_tart.jpg`,
    prepTime: 45,
    servings: "8",
    difficulty: "Medium",
    cuisine: "Mediterranean",
    course: "Dessert",
    tags: ["light-dessert", "pear", "ricotta", "filo tart"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2021-04-17"
  },
  {
    id: "11",
    title: "Chocolate & Whisky Fingers",
    slug: "chocolate-and-whisky-fingers",
    short_description: "No-bake dark-chocolate whisky fingers—silky, rich, cocoa-dusted.",
    image: `${BASE_URL}images/recipes/chocolate_and_whisky_fingers.jpg`,
    prepTime: 45,
    servings: "8",
    difficulty: "Easy",
    cuisine: "European",
    course: "Dessert",
    tags: ["light-dessert", "alcohol", "cocoa", "no-bake"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2021-04-17"
  },
  {
    id: "12",
    title: "Potato-Crusted Swiss Chard Tart",
    slug: "potato-crusted-swiss-chard-tart",
    short_description: "Potato-crusted tart with Swiss chard, onions, garlic, eggs, cream, and mozzarella—golden, soft, and comforting.",
    image: `${BASE_URL}images/recipes/potato_crusted_swiss_chard_tart.jpg`,
    prepTime: 45,
    servings: "8",
    difficulty: "Easy",
    cuisine: "European",
    course: "Main",
    tags: ["vegetarian", "potato crust", "swiss chard", "family dinner"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-10-19"
  },
  {
    id: "13",
    title: "Chocolate, Banana & Apple Syrup Tarte Tatin",
    slug: "chocolate-banana-apple-syrup-tarte-tatin",
    short_description: "Upside-down tart with chocolate, caramelized bananas, and apple syrup.",
    image: `${BASE_URL}images/recipes/chocolate_banana_and_apple_syrup_tarte_tatin.jpg`,
    prepTime: 30,
    servings: "6",
    difficulty: "Medium",
    cuisine: "French",
    course: "Dessert",
    tags: ["chocolate", "banana", "tart"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2020-09-12"
  },
  {
    id: "14",
    title: "Japanese Style Egg Sandwich",
    slug: "japanese-style-egg-sandwich",
    short_description: "Fluffy egg salad sandwich on soft milk bread.",
    image: `${BASE_URL}images/recipes/japanese_style_egg_sandwich.jpg`,
    prepTime: 15,
    servings: "2",
    difficulty: "Easy",
    cuisine: "Japanese",
    course: "Breakfast",
    tags: ["sandwich", "eggs", "japanese"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2020-07-20"
  },
  {
    id: "15",
    title: "Quick Marinated Green Olives (Zeitoun Marsouss)",
    slug: "quick-marinated-green-olives",
    short_description: "Fresh green olives mixed with coarse salt, lemon, chili, and a drop of olive oil. Ready in about five days.",
    image: `${BASE_URL}images/recipes/quick_marinated_green_olives.jpg`,
    prepTime: 10,
    servings: "10",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["olives", "mezze", "quick-pickle", "lemon"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-10-15"
  },
  {
    id: "16",
    title: "Beef Stir-Fry with Mixed Bell Peppers",
    slug: "beef-stir-fry-mixed-bell-peppers",
    short_description: "Quick beef stir-fry with colorful bell peppers.",
    image: `${BASE_URL}images/recipes/beef_stir_fry_mixed_bell_peppers.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Asian",
    course: "Main",
    tags: ["beef", "stir-fry", "quick"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2020-08-10"
  },
  {
    id: "17",
    title: "Mint, Pea and Quinoa Blinis with Lemon Yogurt",
    slug: "mint-pea-quinoa-blinis",
    short_description: "Oven-baked blinis of peas, ricotta, quinoa, and mint with a lemony yogurt sauce.",
    image: `${BASE_URL}images/recipes/mint_pea_quinoa_blinis.jpg`,
    prepTime: 15,
    servings: "8",
    difficulty: "Easy",
    cuisine: "Mediterranean-inspired",
    course: "Breakfast",
    tags: ["blini", "gluten-free", "ricotta", "mint-and-peas"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-09-30"
  },
  {
    id: "18",
    title: "Tahini Pistachio Date Bites",
    slug: "tahini-pistachio-date-bites",
    short_description: "No-bake date and tahini bites rolled in pistachio and cardamom. Naturally sweet.",
    image: `${BASE_URL}images/recipes/tahini_pistachio_date_bites.jpg`,
    prepTime: 15,
    servings: "24",
    difficulty: "Easy",
    cuisine: "Middle Eastern",
    course: "Dessert",
    tags: ["date balls", "tahini", "pistachio", "no-sugar-added"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-09-25"
  },
  {
  id: "19",
  title: "Mini Labneh & Makdouss Cups",
  slug: "mini-labneh-and-makdous-cups",
  short_description: "Bite-sized cups with creamy labneh, tangy makdouss, and fresh mint.",
  image: `${BASE_URL}images/recipes/mini_labneh_makdouss_cups.jpg`,
  prepTime: 15,
  servings: "20–24 mini cups",
  difficulty: "Easy",
  cuisine: "Lebanese",
  course: "Salad & Side",
  tags: ["labneh", "makdouss", "bouchée", "mezze"],
  keywords: ["مكدوس", "لبنة"],
  featured: false,
  rating: 4.8,
  date_published: "2025-11-06"
  },
  {
    id: "20",
    title: "Smoked Salmon Sandwich on Sourdough",
    slug: "smoked-salmon-sandwich-sourdough",
    short_description: "Avocado, cottage cheese with dill, rocket leaves, smoked salmon, and red onion on sourdough.",
    image: `${BASE_URL}images/recipes/smoked_salmon_sandwich.jpg`,
    prepTime: 15,
    servings: "2",
    difficulty: "Easy",
    cuisine: "International",
    course: "Breakfast",
    tags: ["salmon", "sourdough", "avocado", "cottage-cheese", "quick"],
    keywords: ["سندويش سلمون", "خبز العجين المخمر"],
    featured: false,
    rating: 4.7,
    date_published: "2025-09-21"
  },
  {
    id: "21",
    title: "Laban Emmo",
    slug: "laban-emmo",
    short_description: "A comforting Lebanese laban dish with lamb shanks, pearl onions, and pine nuts.",
    image: `${BASE_URL}images/recipes/laban_emmo.jpg`,
    prepTime: 25,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["laban", "lamb", "comfort-food", "stew"],
    keywords: ["لبن امّو", "مرق لبن"],
    featured: false,
    rating: 4.9,
    date_published: "2025-09-16"
  },
  {
    id: "22",
    title: "Lentil Protein Crackers with Moringa",
    slug: "lentil-protein-crackers-moringa",
    short_description: "Crispy, nourishing plant-based crackers boosted with moringa.",
    image: `${BASE_URL}images/recipes/lentil_moringa_crackers.jpg`,
    prepTime: 30,
    servings: "1 large tray (10–12 servings)",
    difficulty: "Easy",
    cuisine: "Healthy",
    course: "Salad & Side",
    tags: ["lentils", "moringa", "gluten-free", "baked", "crackers"],
    keywords: ["مقرمشات العدس"],
    featured: false,
    rating: 4.6,
    date_published: "2025-09-10"
  },
  {
    id: "23",
    title: "Colorful Shrimp Stir-Fry",
    slug: "shrimp-stir-fry",
    short_description: "Juicy shrimp with peppers, zucchini, aromatics, and a quick soy-sesame sauce.",
    image: `${BASE_URL}images/recipes/shrimp_stir_fry.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Asian-Inspired",
    course: "Main",
    tags: ["shrimp", "stir-fry", "quick", "vegetables", "rice"],
    keywords: ["روبيان", "خضار", "قلي سريع"],
    featured: false,
    rating: 4.7,
    date_published: "2025-09-09"
  },
  {
    id: "24",
    title: "Green Bean & Lamb Stew",
    slug: "green-bean-lamb-stew",
    short_description: "Lebanese-style stewed green beans with lamb, tomato, and aromatics.",
    image: `${BASE_URL}images/recipes/green_bean_lamb_stew.jpg`,
    prepTime: 20,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["green-beans", "lamb", "stew", "tomato"],
    keywords: ["لوبيا باللحمة"],
    featured: false,
    rating: 4.6,
    date_published: "2025-09-04"
  },
  {
    id: "25",
    title: "Chard with Black-Eyed Peas (Seleq bi Loubye)",
    slug: "chard-black-eyed-peas",
    short_description: "Tender black-eyed peas, caramelized onions, and fresh lemon juice over chard.",
    image: `${BASE_URL}images/recipes/chard_black_eyed_peas.jpg`,
    prepTime: 25,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["chard", "black-eyed-peas", "vegan", "comfort-food"],
    keywords: ["سلق", "لوبية"],
    featured: false,
    rating: 4.8,
    date_published: "2025-09-01"
  },
  {
    id: "26",
    title: "Shakshouka with Chickpeas",
    slug: "shakshouka-with-chickpeas",
    short_description: "Baked eggs in a spiced fresh-tomato sauce with chickpeas.",
    image: `${BASE_URL}images/recipes/shakshouka_chickpeas.jpg`,
    prepTime: 15,
    servings: "6–8",
    difficulty: "Easy",
    cuisine: "Middle Eastern",
    course: "Breakfast",
    tags: ["eggs", "tomato", "one-pan", "brunch", "chickpeas"],
    keywords: ["شكشوكة"],
    featured: false,
    rating: 4.8,
    date_published: "2025-08-27"
  },
  {
    id: "27",
    title: "3-Ingredient Chocolate-Dipped Banana Pops",
    slug: "chocolate-banana-peanut-butter-pops",
    short_description: "Frozen banana pops filled with peanut butter and dipped in chocolate.",
    image: `${BASE_URL}images/recipes/choco_banana_pops.jpg`,
    prepTime: 15,
    servings: "6 pops",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["no-bake", "frozen", "banana", "chocolate", "peanut-butter"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-08-22"
  },
  {
    id: "28",
    title: "Alayet Bamyeh (Okra with Pomegranate Molasses)",
    slug: "alayet-bamyeh-okra",
    short_description: "Stir-fried okra with roasted cherry tomatoes, onions, chilies, coriander, and pomegranate molasses.",
    image: `${BASE_URL}images/recipes/alayet_bamyeh.jpg`,
    prepTime: 20,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["okra", "pomegranate-molasses", "cherry-tomatoes", "stir-fry"],
    keywords: ["بامية"],
    featured: false,
    rating: 4.7,
    date_published: "2025-08-19"
  },
  {
    id: "29",
    title: "Plum Cake with Vanilla Syrup",
    slug: "plum-cake-vanilla-syrup",
    short_description: "Light, fruity summer cake topped with plums and finished with a warm vanilla syrup.",
    image: `${BASE_URL}images/recipes/plum_cake_vanilla_syrup.jpg`,
    prepTime: 20,
    servings: "8–10",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["cake", "plum", "vanilla", "summer"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-08-15"
  },
  {
    id: "30",
    title: "Stuffed Are3 (Lebanese Wild Squash)",
    slug: "stuffed-are3",
    short_description: "Zesty stuffed wild squash with rice, minced meat, garlic, dried mint, and lemon.",
    image: `${BASE_URL}images/recipes/stuffed_are3.jpg`,
    prepTime: 35,
    servings: "5–6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["squash", "stuffed", "rice", "lemon", "mehshi"],
    keywords: ["قرع بري"],
    featured: false,
    rating: 4.9,
    date_published: "2025-08-07"
  },
  {
    id: "31",
    title: "Loubieh bi Zeit (Green Beans in Olive Oil)",
    slug: "loubieh-bi-zeit",
    short_description: "Roman green beans gently stewed with tomatoes, onions, garlic, and olive oil.",
    image: `${BASE_URL}images/recipes/loubieh_bi_zeit.jpg`,
    prepTime: 20,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["green-beans", "olive-oil", "tomato", "vegan", "stew"],
    keywords: ["لوبية بزيت"],
    featured: false,
    rating: 4.9,
    date_published: "2025-08-04"
  },
  {
    id: "32",
    title: "Toum (Garlic Paste)",
    slug: "toum-garlic-paste",
    short_description: "Classic Lebanese garlic emulsion—light, fluffy, and boldly garlicky.",
    image: `${BASE_URL}images/recipes/toum_garlic_paste.jpg`,
    prepTime: 15,
    servings: "2 cups",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Sauce",
    tags: ["garlic", "sauce", "spread", "emulsion"],
    keywords: ["توم", "ثوم"],
    featured: false,
    rating: 5.0,
    date_published: "2025-07-31"
  },
  {
    id: "33",
    title: "Lebanese Green Bean Salad",
    slug: "lebanese-green-bean-salad",
    short_description: "Old-school side salad: blanched green beans, garlicky verjuice dressing, tomatoes, and optional potatoes.",
    image: `${BASE_URL}images/recipes/lebanese_green_bean_salad.jpg`,
    prepTime: 15,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["green-beans", "verjuice", "salad", "garlic"],
    keywords: ["سلطة فاصوليا"],
    featured: false,
    rating: 4.8,
    date_published: "2025-07-28"
  },
  {
    id: "34",
    title: "Homemade Basil Pesto",
    slug: "homemade-basil-pesto",
    short_description: "Vivid green, lemony pesto you’ll want to put on everything.",
    image: `${BASE_URL}images/recipes/homemade_basil_pesto.jpg`,
    prepTime: 15,
    servings: "2 cups",
    difficulty: "Easy",
    cuisine: "Italian",
    course: "Sauce",
    tags: ["pesto", "basil", "pine-nuts", "no-cook"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-07-22"
  },
  {
    id: "35",
    title: "Oven-Roasted Mixed Vegetables",
    slug: "oven-roasted-mixed-vegetables",
    short_description: "Any veg you like—olive oil, oregano, sea salt, cracked pepper—roasted to perfection.",
    image: `${BASE_URL}images/recipes/oven_roasted_mixed_vegetables.jpg`,
    prepTime: 15,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Mediterranean",
    course: "Salad & Side",
    tags: ["roasted", "vegetables", "sheet-pan", "easy"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2025-07-19"
  },
  {
    id: "36",
    title: "Arroz con Pollo with Chorizo",
    slug: "arroz-con-pollo-chorizo",
    short_description: "Spanish-inspired chicken and rice with peppers, saffron, peas, and chorizo.",
    image: `${BASE_URL}images/recipes/arroz_con_pollo_chorizo.jpg`,
    prepTime: 25,
    servings: "6–8",
    difficulty: "Medium",
    cuisine: "Spanish",
    course: "Main",
    tags: ["chicken", "rice", "one-pot", "saffron", "chorizo"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-07-14"
  },
  {
    id: "37",
    title: "Tabbouleh (Parsley & Bulgur Salad)",
    slug: "tabbouleh-parsley-bulgur-salad",
    short_description: "Curly parsley, fresh mint, tomatoes, lemon, olive oil, and sumac.",
    image: `${BASE_URL}images/recipes/tabbouleh_parsley_bulgur_salad.jpg`,
    prepTime: 25,
    servings: "6–8",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["tabbouleh", "parsley", "mint", "lemon"],
    keywords: ["تبولة"],
    featured: false,
    rating: 4.9,
    date_published: "2025-07-04"
  },
  {
    id: "38",
    title: "Mixed Seed Crackers",
    slug: "mixed-seed-crackers",
    short_description: "Crunchy, nourishing crackers packed with seeds and herbs.",
    image: `${BASE_URL}images/recipes/mixed_seed_crackers.jpg`,
    prepTime: 10,
    servings: "1 tray (12–16 pieces)",
    difficulty: "Easy",
    cuisine: "Healthy",
    course: "Breakfast",
    tags: ["crackers", "seeds", "baked", "gluten-free"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2025-06-28"
  },
  {
    id: "39",
    title: "Grilled Zucchini Salad with Ricotta & Capers",
    slug: "grilled-zucchini-ricotta-capers-salad",
    short_description: "Charred zucchini with a honey-balsamic-oregano vinaigrette, capers, walnuts, and ricotta.",
    image: `${BASE_URL}images/recipes/grilled_zucchini_ricotta_capers_salad.jpg`,
    prepTime: 20,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Mediterranean",
    course: "Salad & Side",
    tags: ["zucchini", "grilled", "ricotta", "capers", "walnuts"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-07-01"
  },
  {
    id: "40",
    title: "Kousa bi Laban (Zucchini with Yogurt Sauce)",
    slug: "kousa-bi-laban",
    short_description: "Seared zucchini stuffed with beef and pine nuts, finished in a garlicky yogurt–tahini sauce.",
    image: `${BASE_URL}images/recipes/kousa_bi_laban.jpg`,
    prepTime: 35,
    servings: "5–6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["zucchini", "yogurt-sauce", "pine-nuts", "baked"],
    keywords: ["كوسا بلبن"],
    featured: false,
    rating: 4.9,
    date_published: "2025-06-22"
  },
  {
    id: "41",
    title: "Sunday Eggs with Garden Greens & Lemon",
    slug: "sunday-eggs-garden-greens-lemon",
    short_description: "Baked eggs with sautéed kale & chard, lemon, sumac, and chili.",
    image: `${BASE_URL}images/recipes/sunday_eggs_garden_greens_lemon.jpg`,
    prepTime: 15,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Breakfast",
    tags: ["eggs", "kale", "chard", "lemon"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-07-16"
  },
  {
    id: "42",
    title: "Tuna Sandwich",
    slug: "tuna-sandwich",
    short_description: "Classic tuna, mayo, and Dijon with herbs, capers, and crisp greens.",
    image: `${BASE_URL}images/recipes/tuna_sandwich.jpg`,
    prepTime: 10,
    servings: "2–3",
    difficulty: "Easy",
    cuisine: "International",
    course: "Main",
    tags: ["sandwich", "tuna", "lunch"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2025-06-16"
  },
  {
    id: "43",
    title: "Mnazlit el Khodra (Vegetable Stew)",
    slug: "mnazlit-el-khodra",
    short_description: "Cozy Lebanese vegetable stew: onion, eggplant, zucchini, peppers, chickpeas, tomato.",
    image: `${BASE_URL}images/recipes/mnazlit_el_khodra.jpg`,
    prepTime: 15,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["stew", "eggplant", "zucchini", "chickpeas", "vegan"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-06-11"
  },
  {
    id: "44",
    title: "Mrabba el Jozz (Green Walnut Preserve)",
    slug: "mrabba-el-jozz",
    short_description: "Traditional green walnut jam—aromatic, glossy, and celebratory.",
    image: `${BASE_URL}images/recipes/mrabba_el_jozz.jpg`,
    prepTime: 60,
    servings: "10–12 jars",
    difficulty: "Advanced",
    cuisine: "Levantine",
    course: "Dessert",
    tags: ["preserve", "walnut", "syrup", "dessert"],
    keywords: ["مربى الجوز"],
    featured: false,
    rating: 4.9,
    date_published: "2025-06-06"
  },
  {
    id: "45",
    title: "Rocky Road Bars",
    slug: "rocky-road-bars",
    short_description: "No-bake chocolate bars with biscuits, marshmallows, pistachios, hazelnuts, and peanuts.",
    image: `${BASE_URL}images/recipes/rocky_road_bars.jpg`,
    prepTime: 15,
    servings: "16 squares",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["no-bake", "chocolate", "bars"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-05-27"
  },
  {
    id: "46",
    title: "Labneh Balls in Olive Oil",
    slug: "labneh-balls-olive-oil",
    short_description: "Rich, tangy labneh rolled into balls and preserved in extra virgin olive oil.",
    image: `${BASE_URL}images/recipes/labneh_balls_olive_oil.jpg`,
    prepTime: 30,
    servings: "2–3 jars",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Sauce",
    tags: ["labneh", "preserve", "mezze"],
    keywords: ["لبنة"],
    featured: false,
    rating: 5.0,
    date_published: "2025-05-25"
  },
  {
    id: "47",
    title: "Mograbieh (Lebanese Couscous with Chicken & Lamb)",
    slug: "mograbieh-lebanese-couscous",
    short_description: "Pearl couscous with spiced broth, lamb shanks, chicken, pearl onions, and chickpeas.",
    image: `${BASE_URL}images/recipes/mograbieh_lebanese_couscous.jpg`,
    prepTime: 40,
    servings: "6–8",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["couscous", "chicken", "lamb", "stew"],
    keywords: ["مغربية"],
    featured: false,
    rating: 4.9,
    date_published: "2025-05-21"
  },
  {
    id: "48",
    title: "Homemade Labneh",
    slug: "homemade-labneh",
    short_description: "Strained yogurt turned into tangy, spreadable labneh.",
    image: `${BASE_URL}images/recipes/homemade_labneh.jpg`,
    prepTime: 10,
    servings: "4 cups",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Sauce",
    tags: ["yogurt", "labneh", "homemade"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-05-19"
  },
  {
    id: "49",
    title: "Homemade Yogurt",
    slug: "homemade-yogurt",
    short_description: "Just milk and a spoon of yogurt—no preservatives, creamy and fresh.",
    image: `${BASE_URL}images/recipes/homemade_yogurt.jpg`,
    prepTime: 10,
    servings: "1 kg",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Sauce",
    tags: ["yogurt", "homemade", "basic"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-05-15"
  },
  {
    id: "50",
    title: "Cauliflower Fatteh with Labban & Tahini",
    slug: "cauliflower-fatteh-labban-tahini",
    short_description: "Roasted cauliflower, chickpeas, and pine nuts layered with garlicky labban–tahini and pomegranate.",
    image: `${BASE_URL}images/recipes/cauliflower_fatteh_labban_tahini.jpg`,
    prepTime: 20,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Middle Eastern",
    course: "Main",
    tags: ["fatteh", "cauliflower", "tahini", "labban"],
    keywords: ["فتة"],
    featured: false,
    rating: 4.8,
    date_published: "2025-05-13"
  },
  {
    id: "51",
    title: "Four-Layer Chocolate Cake",
    slug: "four-layer-chocolate-cake",
    short_description: "Moist, rich chocolate cake finished with a glossy dark-chocolate ganache.",
    image: `${BASE_URL}images/recipes/four_layer_chocolate_cake.jpg`,
    prepTime: 25,
    servings: "10–12",
    difficulty: "Medium",
    cuisine: "International",
    course: "Dessert",
    tags: ["chocolate cake", "layer cake", "ganache"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-05-06"
  },
  {
    id: "52",
    title: "Lebanese Spinach with Beef & Lemon",
    slug: "lebanese-spinach-with-beef",
    short_description: "Spinach sauté with onions, ground beef, lemon, and pine nuts.",
    image: `${BASE_URL}images/recipes/lebanese_spinach_with_beef.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["spinach", "beef", "lemon"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-05-01"
  },
  {
    id: "53",
    title: "Warm Fava Bean & Chickpea Bowl (Foul Mdammas)",
    slug: "foul-mdammas-with-chickpeas",
    short_description: "Hearty breakfast of warm favas and chickpeas with garlic, lemon, and olive oil.",
    image: `${BASE_URL}images/recipes/foul_mdammas_with_chickpeas.jpg`,
    prepTime: 10,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Breakfast",
    tags: ["foul", "beans", "breakfast"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-04-29"
  },
  {
    id: "54",
    title: "Halloumi Guacamole & Poached Egg Stack",
    slug: "halloumi-guacamole-egg-stack",
    short_description: "Crispy grilled halloumi layered with fresh guacamole and a silky poached egg.",
    image: `${BASE_URL}images/recipes/halloumi_guacamole_egg_stack.jpg`,
    prepTime: 10,
    servings: "2",
    difficulty: "Easy",
    cuisine: "Levantine",
    course: "Breakfast",
    tags: ["halloumi", "poached egg", "guacamole"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-04-25"
  },
  {
    id: "55",
    title: "Pumpkin & Sage Pasta",
    slug: "pumpkin-sage-pasta",
    short_description: "Silky pumpkin sauce with crispy sage tossed through pasta—simple and cozy.",
    image: `${BASE_URL}images/recipes/pumpkin_sage_pasta.jpg`,
    prepTime: 10,
    servings: "3–4",
    difficulty: "Easy",
    cuisine: "International",
    course: "Main",
    tags: ["pumpkin", "sage", "one-pot pasta"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2025-04-23"
  },
  {
    id: "56",
    title: "No-Bake Mini Egg Cheesecake",
    slug: "no-bake-mini-egg-cheesecake",
    short_description: "Creamy, light no-bake cheesecake topped with pistachio cream and mini chocolate bunnies.",
    image: `${BASE_URL}images/recipes/no_bake_mini_egg_cheesecake.jpg`,
    prepTime: 25,
    servings: "8–10",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["cheesecake", "no-bake", "easter", "pistachio", "chocolate"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2024-04-15"
  },
  {
    id: "57",
    title: "Pumpkin Kibbeh Tart (Two Fillings)",
    slug: "pumpkin-kibbeh-tart-two-fillings",
    short_description: "A modern single-layer pumpkin kibbeh with your choice of two savory fillings.",
    image: `${BASE_URL}images/recipes/pumpkin_kibbeh_tart_two_fillings.jpg`,
    prepTime: 30,
    servings: "8",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["kibbeh", "pumpkin", "baked", "lebanese"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-04-13"
  },
  {
    id: "58",
    title: "Riz 3a Djej (Chicken and Rice)",
    slug: "riz-3a-djej-chicken-and-rice",
    short_description: "Butter-scented rice topped with juicy organic chicken, spices, and nuts.",
    image: `${BASE_URL}images/recipes/riz_3a_djej_chicken_and_rice.jpg`,
    prepTime: 20,
    servings: "6–8",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["chicken", "rice", "comfort-food", "lebanese"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2024-04-08"
  },
  {
    id: "59",
    title: "Homemade Halloumi Cheese",
    slug: "homemade-halloumi-cheese",
    short_description: "Step-by-step halloumi made at home with simple ingredients.",
    image: `${BASE_URL}images/recipes/homemade_halloumi_cheese.jpg`,
    prepTime: 30,
    servings: "12 pieces",
    difficulty: "Advanced",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["cheese", "halloumi", "from-scratch", "preserving"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2024-04-05"
  },
  {
    id: "60",
    title: "Mjadara (Brown Lentil Purée)",
    slug: "mjadara-brown-lentil-puree",
    short_description: "A traditional Lebanese lentil dish—simple, hearty, and deeply comforting.",
    image: `${BASE_URL}images/recipes/mjadara_brown_lentil_puree.jpg`,
    prepTime: 10,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["lentils", "vegetarian", "comfort-food", "lebanese"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2024-04-02"
  },
  {
    id: "61",
    title: "Mdardara (Lentils with Rice & Caramelized Onions)",
    slug: "mdardara-lentils-with-rice-and-onions",
    short_description: "A beloved Lebanese staple—lentils and rice finished with sweet caramelized onions.",
    image: `${BASE_URL}images/recipes/mdardara_lentils_with_rice_and_onions.jpg`,
    prepTime: 15,
    servings: "6–8",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["lentils", "rice", "vegan", "lebanese", "comfort-food"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-03-31"
  },
  {
    id: "62",
    title: "Grilled Calamari Salad",
    slug: "grilled-calamari-salad",
    short_description: "Tender marinated calamari grilled and served over fresh salad—lean protein, big flavor.",
    image: `${BASE_URL}images/recipes/grilled_calamari_salad.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["seafood", "grilled", "salad", "healthy"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2024-03-27"
  },
  {
    id: "63",
    title: "Bulgur bi Dfin",
    slug: "bulgur-bi-dfin",
    short_description: "Traditional bulgur cooked under pressure with chickpeas, lamb flavors, and warm spices.",
    image: `${BASE_URL}images/recipes/bulgur_bi_dfin.jpg`,
    prepTime: 20,
    servings: "6–8",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["bulgur", "chickpeas", "comfort-food", "pressure-cooker"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-03-25"
  },
  {
    id: "64",
    title: "Rice Pudding with Strawberries & Pistachios",
    slug: "rice-pudding-with-strawberries-and-pistachios",
    short_description: "Turn leftover rice into the most delicious rice pudding with cream, honey, and vanilla.",
    image: `${BASE_URL}images/recipes/rice_pudding_with_strawberries_and_pistachios.jpg`,
    prepTime: 10,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Dessert",
    tags: ["rice-pudding", "strawberry", "pistachio", "leftovers"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2024-03-23"
  },
  {
    id: "65",
    title: "Chocolate Granola",
    slug: "chocolate-granola",
    short_description: "Crispy, chocolatey, nutty granola you’ll love—easy to bake and hard to stop eating.",
    image: `${BASE_URL}images/recipes/chocolate_granola.jpg`,
    prepTime: 15,
    servings: "12 (about 6 cups)",
    difficulty: "Easy",
    cuisine: "International",
    course: "Breakfast",
    tags: ["granola", "breakfast", "snack", "chocolate", "baked"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2024-03-17"
  },
  {
    id: "66",
    title: "Eress 3anneh Salad (Sea Holly)",
    slug: "eress-3anneh-salad-sea-holly",
    short_description: "Crisp, peppery Eress 3anneh with fennel, onion, radishes, cabbage, and a bright lemon-vinegar dressing.",
    image: `${BASE_URL}images/recipes/eress_3anneh_salad.jpg`,
    prepTime: 20,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["salad", "wild-greens", "lebanese", "spring"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2024-03-14"
  },
  {
    id: "67",
    title: "Taro with Lentils (Kilkass bi 3adass)",
    slug: "taro-with-lentils-kilkass-bi-3adass",
    short_description: "A comforting Lebanese taro and brown lentil stew finished with lemon and garlic.",
    image: `${BASE_URL}images/recipes/taro_with_lentils.jpg`,
    prepTime: 15,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["taro", "lentils", "stew", "lebanese", "vegan"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-03-11"
  },
  {
    id: "68",
    title: "Salty Cheddar Biscuits (Not Sweet)",
    slug: "salty-cheddar-biscuits",
    short_description: "Savory, puffy cheddar-parmesan biscuits with a hint of smoked paprika—perfect snack or side.",
    image: `${BASE_URL}images/recipes/salty_cheddar_biscuits.jpg`,
    prepTime: 15,
    servings: "6–8",
    difficulty: "Easy",
    cuisine: "International",
    course: "Bread",
    tags: ["biscuits", "savory", "cheddar", "parmesan", "snack"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2024-03-09"
  },
  {
    id: "69",
    title: "Khebbayzeh with Chickpeas (Wild Herb)",
    slug: "khebbayzeh-with-chickpeas-wild-herb",
    short_description: "Simple dish of wild Khebbayzeh greens with soft chickpeas, onions, and lemon.",
    image: `${BASE_URL}images/recipes/khebbayzeh_with_chickpeas.jpg`,
    prepTime: 20,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["wild-greens", "chickpeas", "lemon", "vegan", "comfort-food"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-03-07"
  },
  {
    id: "70",
    title: "Lentil Soup with Bulgur Bites",
    slug: "lentil-soup-with-bulgur-bites",
    short_description: "Hearty brown-lentil soup served with soft bulgur-herb bites and a bright lemon finish.",
    image: `${BASE_URL}images/recipes/lentil_soup_with_bulgur_bites.jpg`,
    prepTime: 25,
    servings: "6–8",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["lentil-soup", "bulgur", "lemon", "comfort-food", "meatless"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2024-03-05"
  },
  {
    id: "71",
    title: "Sourdough Sandwich Trio",
    slug: "sourdough-sandwich-trio",
    short_description: "Three vibrant sandwiches—tuna/beetroot, burrata-tomato-garlic confit, and smoked salmon—crafted on sourdough.",
    image: `${BASE_URL}images/recipes/sourdough_sandwich_trio.jpg`,
    prepTime: 25,
    servings: "3–4",
    difficulty: "Easy",
    cuisine: "International",
    course: "Bread",
    tags: ["sandwich", "sourdough", "tuna", "burrata", "smoked-salmon"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-03-03"
  },
  {
    id: "72",
    title: "Chocolate Cake with Glossy Glaze",
    slug: "chocolate-cake-with-glossy-glaze",
    short_description: "Super easy, deeply chocolatey Bundt cake with a luscious dark-chocolate glaze.",
    image: `${BASE_URL}images/recipes/chocolate_cake_with_glaze.jpg`,
    prepTime: 25,
    servings: "12",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["chocolate", "cake", "bundt", "glaze", "baking"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2024-03-01"
  },
  {
    id: "73",
    title: "Chard Stems with Tahini",
    slug: "chard-stems-with-tahini",
    short_description: "Tender chard stems tossed in a tangy garlic-lemon tahini sauce—simple and nostalgic.",
    image: `${BASE_URL}images/recipes/chard_stems_with_tahini.jpg`,
    prepTime: 15,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["chard", "tahini", "lemon", "garlic", "lenten"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2024-02-26"
  },
  {
    id: "74",
    title: "Upside Down Date & Coffee Cake",
    slug: "upside-down-date-and-coffee-cake",
    short_description: "Caramelized date top with a moist coffee-almond cake—unique, memorable, and so good.",
    image: `${BASE_URL}images/recipes/upside_down_date_coffee_cake.jpg`,
    prepTime: 25,
    servings: "10–12",
    difficulty: "Medium",
    cuisine: "International",
    course: "Dessert",
    tags: ["date-cake", "coffee", "almond", "upside-down", "baking"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2024-02-24"
  },
  {
    id: "75",
    title: "Millefeuille Nabe (Layered Hot Pot)",
    slug: "millefeuille-nabe-layered-hot-pot",
    short_description: "Delicate layers of Napa cabbage, bok choy, beef or pork belly, and enoki mushrooms in a savory broth.",
    image: `${BASE_URL}images/recipes/millefeuille_nabe_hot_pot.jpg`,
    prepTime: 25,
    servings: "4–6",
    difficulty: "Medium",
    cuisine: "Japanese",
    course: "Main",
    tags: ["hot-pot", "cabbage", "enoki", "beef", "comfort-food"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-02-21"
  },
  {
    id: "76",
    title: "No-Bake Date Peanut Bars",
    slug: "no-bake-date-peanut-bars",
    short_description: "Chewy date–peanut butter layer with puffed rice and peanuts, topped with milk chocolate.",
    image: `${BASE_URL}images/recipes/no_bake_date_peanut_bars.jpg`,
    prepTime: 20,
    servings: "16 bars",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["no-bake", "dates", "peanut-butter", "snack", "kids"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-02-18"
  },
  {
    id: "77",
    title: "Khebzit Souraya (Greek Tsoureki)",
    slug: "khebzit-souraya-greek-tsoureki",
    short_description: "Soft, fragrant braided Easter bread flavored with mahlepi, mastic, and orange.",
    image: `${BASE_URL}images/recipes/khezbit_souraya_tsoureki.jpg`,
    prepTime: 30,
    servings: "1 large loaf",
    difficulty: "Medium",
    cuisine: "Greek",
    course: "Bread",
    tags: ["easter-bread", "tsoureki", "mahlepi", "mastic", "braided"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-02-12"
  },
  {
    id: "78",
    title: "Broccoli Gratin with Ricotta",
    slug: "broccoli-gratin-with-ricotta",
    short_description: "Rescue yellowing broccoli with this easy béchamel gratin—cheddar inside, ricotta on top.",
    image: `${BASE_URL}images/recipes/broccoli_gratin_ricotta.jpg`,
    prepTime: 15,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "International",
    course: "Salad & Side",
    tags: ["broccoli", "gratin", "bechamel", "cheddar", "ricotta"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2025-02-08"
  },
  {
    id: "79",
    title: "Maqloubeh Batenjen (Eggplant Maqloubeh)",
    slug: "maqloubeh-batenjen-eggplant",
    short_description: "A show-stopping upside-down rice with eggplant, cauliflower, carrots, and chicken.",
    image: `${BASE_URL}images/recipes/maqloubeh_batenjen.jpg`,
    prepTime: 45,
    servings: "8–10",
    difficulty: "Advanced",
    cuisine: "Levantine",
    course: "Main",
    tags: ["maqloubeh", "eggplant", "rice", "chicken", "feast"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-02-05"
  },
  {
    id: "80",
    title: "Roasted Cauliflower, Chickpea & Spinach Salad",
    slug: "roasted-cauliflower-chickpea-spinach-salad",
    short_description: "Bold flavors and crunchy textures—seeds, spices, dates, and greens make this a satisfying main or side.",
    image: `${BASE_URL}images/recipes/roasted_cauliflower_chickpea_spinach_salad.jpg`,
    prepTime: 20,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "Middle Eastern",
    course: "Salad & Side",
    tags: ["cauliflower", "chickpeas", "dates", "seeds", "salad"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2025-02-02"
  },
  {
    id: "81",
    title: "Caramel Sea Salt Chocolate Cookies",
    slug: "caramel-sea-salt-chocolate-cookies",
    short_description: "Chunky, chocolatey cookies dotted with caramel sea salt pieces—crispy edges, soft centers.",
    image: `${BASE_URL}images/recipes/caramel_sea_salt_chocolate_cookies.jpg`,
    prepTime: 20,
    servings: "9 large cookies",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["cookies", "chocolate", "caramel", "sea-salt", "baking"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-01-30"
  },
  {
    id: "82",
    title: "Veg-Peel Crisps with Curry Salt",
    slug: "veg-peel-crisps-with-curry-salt",
    short_description: "Crispy baked peels (carrot, parsnip, potato, radish) tossed in an easy curry salt.",
    image: `${BASE_URL}images/recipes/veg_peel_crisps_curry_salt.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "International",
    course: "Salad & Side",
    tags: ["snack", "crisps", "baked", "veggies", "curry"],
    keywords: [],
    featured: false,
    rating: 4.5,
    date_published: "2025-01-29"
  },
  {
    id: "83",
    title: "Stuffed Silverbeet Leaves (Selek Mehshi)",
    slug: "stuffed-silverbeet-leaves-selek-mehshi",
    short_description: "Tender chard leaves filled with rice, chickpeas, tomato, parsley, and mint—finished with lemon.",
    image: `${BASE_URL}images/recipes/stuffed_silverbeet_leaves.jpg`,
    prepTime: 35,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["chard", "stuffed", "rice", "chickpeas", "lemon"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-01-26"
  },
  {
    id: "84",
    title: "Broccoli–Pumpkin Goat-Cheese Tart (Almond Crust)",
    slug: "broccoli-pumpkin-goat-cheese-tart-almond-crust",
    short_description: "Carb-light tart with a broccoli-Parmesan–almond crust, roasted pumpkin, and goat cheese.",
    image: `${BASE_URL}images/recipes/broccoli_pumpkin_goat_cheese_tart.jpg`,
    prepTime: 25,
    servings: "8",
    difficulty: "Medium",
    cuisine: "International",
    course: "Main",
    tags: ["gluten-free", "almond-crust", "pumpkin", "goat-cheese"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2025-01-23"
  },
  {
    id: "85",
    title: "Triple-Layer Chocolate Coconut Bars",
    slug: "triple-layer-chocolate-coconut-bars",
    short_description: "Date-walnut cocoa base, creamy coconut middle, and a glossy chocolate top.",
    image: `${BASE_URL}images/recipes/triple_layer_chocolate_coconut_bars.jpg`,
    prepTime: 25,
    servings: "20 squares",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["no-bake", "dates", "coconut", "snack-bar", "gluten-free"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-01-20"
  },
  {
    id: "86",
    title: "Beef & Broccoli Stir-Fry",
    slug: "beef-and-broccoli-stir-fry",
    short_description: "Tender steak, crisp broccoli, and a glossy garlic–ginger sauce. Better than takeout.",
    image: `${BASE_URL}images/recipes/beef_broccoli_stir_fry.jpg`,
    prepTime: 20,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Chinese",
    course: "Main",
    tags: ["stir-fry", "beef", "broccoli", "weeknight", "one-pan"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-01-13"
  },
  {
    id: "87",
    title: "Dauphinoise with Brie, Caramelized Onions & Gruyère",
    slug: "dauphinoise-brie-caramelized-onions-gruyere",
    short_description: "Silky potato gratin layered with caramelized onions, thyme, Gruyère, and a gooey brie top.",
    image: `${BASE_URL}images/recipes/dauphinoise_brie_caramelized_onions_gruyere.jpg`,
    prepTime: 30,
    servings: "8",
    difficulty: "Medium",
    cuisine: "French",
    course: "Salad & Side",
    tags: ["potatoes", "gratin", "brie", "gruyere", "thyme"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-01-10"
  },
  {
    id: "88",
    title: "Baba Ghanouj (Smoky Eggplant Dip)",
    slug: "baba-ghanouj-smoky-eggplant-dip",
    short_description: "Charred aubergines mashed by hand with tahini, lemon, garlic, and olive oil—garnished with pomegranate.",
    image: `${BASE_URL}images/recipes/baba_ghanouj_smoky_eggplant_dip.jpg`,
    prepTime: 15,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Levantine",
    course: "Sauce",
    tags: ["dip", "eggplant", "tahini", "mezze", "vegan"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2025-01-07"
  },
  {
    id: "89",
    title: "Chicken Fennel Lettuce Cups",
    slug: "chicken-fennel-lettuce-cups",
    short_description: "Zesty chicken salad with capers and olives spooned into crisp lettuce leaves.",
    image: `${BASE_URL}images/recipes/chicken_fennel_lettuce_cups.jpg`,
    prepTime: 20,
    servings: "6–8",
    difficulty: "Easy",
    cuisine: "International",
    course: "Salad & Side",
    tags: ["lettuce-cups", "chicken-salad", "fennel", "appetizer"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2025-01-04"
  },
  {
    id: "90",
    title: "Vanilla Bean Panna Cotta (Cup Version)",
    slug: "vanilla-bean-panna-cotta",
    short_description: "Snow-white panna cotta infused with real vanilla seeds and topped with fresh raspberries.",
    image: `${BASE_URL}images/recipes/vanilla_bean_panna_cotta.jpg`,
    prepTime: 15,
    servings: "8 cups",
    difficulty: "Easy",
    cuisine: "Italian",
    course: "Dessert",
    tags: ["panna-cotta", "vanilla", "make-ahead", "no-bake"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2025-01-02"
  },
  {
    id: "91",
    title: "Crispy Prosciutto & Greens with Maple–Buttermilk Dijon",
    slug: "crispy-prosciutto-greens-maple-buttermilk-dijon",
    short_description: "Roasted jambon de Parme shards over fresh garden greens with a tangy maple–buttermilk dressing.",
    image: `${BASE_URL}images/recipes/crispy_prosciutto_greens_salad.jpg`,
    prepTime: 15,
    servings: "4–6",
    difficulty: "Easy",
    cuisine: "International",
    course: "Salad & Side",
    tags: ["prosciutto", "salad", "maple", "buttermilk", "dijon"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2024-12-28"
  },
  {
    id: "92",
    title: "Christmas Trifle Loaf (Mascarpone & Berries)",
    slug: "christmas-trifle-loaf-mascarpone-berries",
    short_description: "A simpler, spectacular trifle built in a loaf tin—sponge fingers, mascarpone cream, and berries.",
    image: `${BASE_URL}images/recipes/christmas_trifle_loaf.jpg`,
    prepTime: 25,
    servings: "10–12",
    difficulty: "Easy",
    cuisine: "International",
    course: "Dessert",
    tags: ["trifle", "mascarpone", "berries", "no-bake", "christmas"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2024-12-23"
  },
  {
    id: "93",
    title: "Kebbeh bel Sayniyeh (Tray Kebbeh)",
    slug: "kebbeh-bel-sayniyeh-tray-kebbeh",
    short_description: "Classic baked kebbeh: bulgur–meat shell layered with spiced lamb and pine nuts.",
    image: `${BASE_URL}images/recipes/kebbeh_bel_sayniyeh.jpg`,
    prepTime: 40,
    servings: "8",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["kebbeh", "bulgur", "lamb", "pine-nuts", "baked"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2024-12-21"
  },
  {
    id: "94",
    title: "Sheikh el Mehshi (Stuffed Baby Eggplants)",
    slug: "sheikh-el-mehshi-stuffed-eggplants",
    short_description: "Baby eggplants stuffed with spiced meat and pine nuts, nestled on tomato sauce—garnished with pomegranate.",
    image: `${BASE_URL}images/recipes/sheikh_el_mehshi_stuffed_eggplants.jpg`,
    prepTime: 30,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["eggplant", "stuffed", "pine-nuts", "tomato-sauce"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2024-12-19"
  },
  {
    id: "95",
    title: "Poached Pear Ricotta Almond Cake",
    slug: "poached-pear-ricotta-almond-cake",
    short_description: "Tender almond–ricotta cake studded with cinnamon-poached pears; snowy icing sugar finish.",
    image: `${BASE_URL}images/recipes/poached_pear_ricotta_almond_cake.jpg`,
    prepTime: 25,
    servings: "10–12",
    difficulty: "Medium",
    cuisine: "International",
    course: "Dessert",
    tags: ["pear", "ricotta", "almond", "cake", "christmas"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2024-12-17"
  },
  {
    id: "96",
    title: "Chicken Mushroom Noodle Bake",
    slug: "chicken-mushroom-noodle-bake",
    short_description: "Creamy, cozy nouille bake with chicken, sautéed mushrooms, and a Parm-white sauce.",
    image: `${BASE_URL}images/recipes/chicken_mushroom_noodle_bake.jpg`,
    prepTime: 25,
    servings: "6",
    difficulty: "Medium",
    cuisine: "International",
    course: "Main",
    tags: ["pasta bake", "chicken", "comfort food", "mushrooms"],
    keywords: ["nouille", "tagliatelle", "white sauce", "gratin"],
    featured: false,
    rating: 4.8,
    date_published: "2024-12-12"
  },
  {
    id: "97",
    title: "Avocado Cucumber Lettuce Cups",
    slug: "avocado-cucumber-lettuce-cups",
    short_description: "Light, fresh cups of Chinese cabbage with a crunchy avocado–cucumber mix.",
    image: `${BASE_URL}images/recipes/avocado_cucumber_lettuce_cups.jpg`,
    prepTime: 15,
    servings: "12 cups",
    difficulty: "Easy",
    cuisine: "Asian-Inspired",
    course: "Salad & Side",
    tags: ["appetizer", "no-cook", "fresh", "sesame"],
    keywords: ["lettuce cups", "cucumber salad"],
    featured: false,
    rating: 4.7,
    date_published: "2024-12-09"
  },
  {
    id: "98",
    title: "Beetroot, Walnut, Pomegranate & Fig Salad",
    slug: "beetroot-walnut-pomegranate-fig-salad",
    short_description: "Vibrant roasted-beet salad with candied walnuts, figs, sorrel, and a tangy goat-cheese dressing.",
    image: `${BASE_URL}images/recipes/beetroot_walnut_pomegranate_fig_salad.jpg`,
    prepTime: 20,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Mediterranean",
    course: "Salad & Side",
    tags: ["salad", "beetroot", "goat cheese", "holiday"],
    keywords: ["pomegranate", "fig salad"],
    featured: false,
    rating: 4.8,
    date_published: "2024-12-02"
  },
  {
    id: "99",
    title: "Chocolate Chunk Cookies",
    slug: "chocolate-chunk-cookies",
    short_description: "Big bakery-style cookies packed with dark and strawberry chocolate chips.",
    image: `${BASE_URL}images/recipes/ultimate_chocolate_chunk_cookies.jpg`,
    prepTime: 15,
    servings: "6 large cookies",
    difficulty: "Easy",
    cuisine: "American",
    course: "Dessert",
    tags: ["cookies", "chocolate", "baking"],
    keywords: ["chunk cookies", "strawberry chips"],
    featured: false,
    rating: 4.9,
    date_published: "2024-11-25"
  },
  {
    id: "100",
    title: "Popcorn Honeycomb on Caramel Popcorn",
    slug: "popcorn-honeycomb-on-caramel-popcorn",
    short_description: "Ridiculously fun honeycomb poured over caramel popcorn — smash into shards and share.",
    image: `${BASE_URL}images/recipes/popcorn_honeycomb_caramel_popcorn.jpg`,
    prepTime: 15,
    servings: "8",
    difficulty: "Medium",
    cuisine: "International",
    course: "Dessert",
    tags: ["honeycomb", "popcorn", "candy", "kids"],
    keywords: ["caramel popcorn", "homemade honeycomb"],
    featured: false,
    rating: 4.8,
    date_published: "2024-11-21"
  }

];

export async function fetchRecipesIndex(): Promise<RecipeIndexItem[]> {
  // Return data synchronously wrapped in a Promise for immediate loading
  return Promise.resolve(recipesData);
}
