const BASE_URL = import.meta.env.BASE_URL || '/';

export interface RecipeIndexItem {
  id: string;
  title: string;
  slug: string;
  short_description: string;
  image: string;
  prepTime: number;
  servings: string;
  difficulty: "Easy" | "Medium" | "Advanced";
  cuisine: string;
  course: "Breakfast" | "Main" | "Dessert" | "Salad & Side" | "Bread" | "Sauce";
  tags: string[];
  keywords?: string[];
  featured: boolean;
  rating?: number;
  date_published: string;
}

const recipesData: RecipeIndexItem[] = [
  {
    id: "1",
    title: "Mehcheh Coussa",
    slug: "mehcheh-coussa",
    short_description: "Stuffed zucchinis cooked in tomato sauce.",
    image: `${BASE_URL}images/recipes/mehche_coussa.jpg`,
    prepTime: 30,
    servings: "4",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["coussa", "mehche", "zucchinis"],
    keywords: ["كوسة"],
    featured: true,
    rating: 4.8,
    date_published: "2025-05-31"
  },
  {
    id: "2",
    title: "Sayyadiyeh",
    slug: "sayyadiyeh",
    short_description: "Perfectly cooked white fish with marinated rice.",
    image: `${BASE_URL}images/recipes/sayyadiyeh.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Advanced",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["seafood", "healthy", "fish"],
    keywords: ["صيادية"],
    featured: true,
    rating: 4.9,
    date_published: "2025-10-10"
  },
  {
    id: "3",
    title: "Cooked Artichokes",
    slug: "cooked-artichokes",
    short_description: "Cooked artichokes Lebanese mezze",
    image: `${BASE_URL}images/recipes/cooked_artichokes.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["artichokes", "mezze", "side"],
    keywords: [],
    featured: true,
    rating: 5.0,
    date_published: "2020-05-06"
  },
  {
    id: "4",
    title: "Roast Beef",
    slug: "roast-beef",
    short_description: "Garlic-studded roast beef with green beans, mash, and silky pan gravy.",
    image: `${BASE_URL}images/recipes/Roast_beef.jpg`,
    prepTime: 20,
    servings: "4",
    difficulty: "Advanced",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["main", "roast beef"],
    keywords: [],
    featured: true,
    rating: 4.7,
    date_published: "2020-04-25"
  },
  {
    id: "5",
    title: "Chocolate & Red Berries Cupcakes",
    slug: "chocoalte-and-red-berries-cupcakes",
    short_description: "Rich chocolate cupcakes with fresh red berries.",
    image: `${BASE_URL}images/recipes/Chocolate_and_red_berries_cupcakes.jpg`,
    prepTime: 30,
    servings: "12",
    difficulty: "Easy",
    cuisine: "European",
    course: "Dessert",
    tags: ["chocolate", "berries", "cupcakes"],
    keywords: [],
    featured: true,
    rating: 4.9,
    date_published: "2020-05-02"
  },
  {
    id: "6",
    title: "Small Fluffy Japanese Milk Buns (Tangzhong)",
    slug: "small-fluffy-japanese-milk-buns",
    short_description: "Fluffy Japanese milk buns (tangzhong)—pillowy, lightly sweet, golden and soft.",
    image: `${BASE_URL}images/recipes/small_japanese_pain_au_lait.jpg`,
    prepTime: 15,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Japanese",
    course: "Breakfast",
    tags: ["breakfast", "japanese", "bread"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2020-04-15"
  },
  {
    id: "7",
    title: "Loubiyeh bi Zeit",
    slug: "loubiyeh-bi-zeit",
    short_description: "Lebanese green beans cooked in olive oil and tomatoes.",
    image: `${BASE_URL}images/recipes/Loubiyeh_bi_zeit.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["vegan", "healthy", "beans"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2020-05-15"
  },
  {
    id: "8",
    title: "Kebbit Batata",
    slug: "kebbit-batata",
    short_description: "Lebanese potato kibbeh with meat filling.",
    image: `${BASE_URL}images/recipes/kebbit_batata.jpg`,
    prepTime: 45,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["potato", "kibbeh", "traditional"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2020-06-01"
  },
  {
    id: "9",
    title: "Maple Glazed Walnut & Sugar Bun",
    slug: "maple-glazed-walnut-and-sugar-bun",
    short_description: "Maple-glazed walnut cinnamon bun—buttery, nutty, and beautifully swirled.",
    image: `${BASE_URL}images/recipes/maple_glazed_walnut_and_sugar_bun.jpg`,
    prepTime: 5,
    servings: "8",
    difficulty: "Medium",
    cuisine: "European",
    course: "Dessert",
    tags: ["dessert", "cinnamon bun", "sweet"],
    keywords: [],
    featured: false,
    rating: 4.7,
    date_published: "2021-04-09"
  },
  {
    id: "10",
    title: "Pear & Ricotta Tart",
    slug: "pear-and-ricotta-tart",
    short_description: "Flaky filo tart with ricotta, pears, and a touch of brown sugar.",
    image: `${BASE_URL}images/recipes/pear_and_ricotta_tart.jpg`,
    prepTime: 45,
    servings: "8",
    difficulty: "Medium",
    cuisine: "Mediterranean",
    course: "Dessert",
    tags: ["light-dessert", "pear", "ricotta", "filo tart"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2021-04-17"
  },
  {
    id: "11",
    title: "Chocolate & Whisky Fingers",
    slug: "chocolate-and-whisky-fingers",
    short_description: "No-bake dark-chocolate whisky fingers—silky, rich, cocoa-dusted.",
    image: `${BASE_URL}images/recipes/chocolate_and_whisky_fingers.jpg`,
    prepTime: 45,
    servings: "8",
    difficulty: "Easy",
    cuisine: "European",
    course: "Dessert",
    tags: ["light-dessert", "alcohol", "cocoa", "no-bake"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2021-04-17"
  },
  {
    id: "12",
    title: "Potato-Crusted Swiss Chard Tart",
    slug: "potato-crusted-swiss-chard-tart",
    short_description: "Potato-crusted tart with Swiss chard, onions, garlic, eggs, cream, and mozzarella—golden, soft, and comforting.",
    image: `${BASE_URL}images/recipes/potato_crusted_swiss_chard_tart.jpg`,
    prepTime: 45,
    servings: "8",
    difficulty: "Easy",
    cuisine: "European",
    course: "Main",
    tags: ["vegetarian", "potato crust", "swiss chard", "family dinner"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-10-19"
  },
  {
    id: "13",
    title: "Chocolate, Banana & Apple Syrup Tarte Tatin",
    slug: "chocolate-banana-apple-syrup-tarte-tatin",
    short_description: "Upside-down tart with chocolate, caramelized bananas, and apple syrup.",
    image: `${BASE_URL}images/recipes/chocolate_banana_and_apple_syrup_tarte_tatin.jpg`,
    prepTime: 30,
    servings: "6",
    difficulty: "Medium",
    cuisine: "French",
    course: "Dessert",
    tags: ["chocolate", "banana", "tart"],
    keywords: [],
    featured: false,
    rating: 4.8,
    date_published: "2020-09-12"
  },
  {
    id: "14",
    title: "Japanese Style Egg Sandwich",
    slug: "japanese-style-egg-sandwich",
    short_description: "Fluffy egg salad sandwich on soft milk bread.",
    image: `${BASE_URL}images/recipes/japanese_style_egg_sandwich.jpg`,
    prepTime: 15,
    servings: "2",
    difficulty: "Easy",
    cuisine: "Japanese",
    course: "Breakfast",
    tags: ["sandwich", "eggs", "japanese"],
    keywords: [],
    featured: false,
    rating: 4.9,
    date_published: "2020-07-20"
  },
  {
    id: "15",
    title: "Quick Marinated Green Olives (Zeitoun Marsouss)",
    slug: "quick-marinated-green-olives",
    short_description: "Fresh green olives mixed with coarse salt, lemon, chili, and a drop of olive oil. Ready in about five days.",
    image: `${BASE_URL}images/recipes/quick_marinated_green_olives.jpg`,
    prepTime: 10,
    servings: "10",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Salad & Side",
    tags: ["olives", "mezze", "quick-pickle", "lemon"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-10-15"
  },
  {
    id: "16",
    title: "Beef Stir-Fry with Mixed Bell Peppers",
    slug: "beef-stir-fry-mixed-bell-peppers",
    short_description: "Quick beef stir-fry with colorful bell peppers.",
    image: `${BASE_URL}images/recipes/beef_stir_fry_mixed_bell_peppers.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Asian",
    course: "Main",
    tags: ["beef", "stir-fry", "quick"],
    keywords: [],
    featured: false,
    rating: 4.6,
    date_published: "2020-08-10"
  },
  {
    id: "17",
    title: "Mint, Pea and Quinoa Blinis with Lemon Yogurt",
    slug: "mint-pea-quinoa-blinis",
    short_description: "Oven-baked blinis of peas, ricotta, quinoa, and mint with a lemony yogurt sauce.",
    image: `${BASE_URL}images/recipes/mint_pea_quinoa_blinis.jpg`,
    prepTime: 15,
    servings: "8",
    difficulty: "Easy",
    cuisine: "Mediterranean-inspired",
    course: "Breakfast",
    tags: ["blini", "gluten-free", "ricotta", "mint-and-peas"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-09-30"
  },
  {
    id: "18",
    title: "Tahini Pistachio Date Bites",
    slug: "tahini-pistachio-date-bites",
    short_description: "No-bake date and tahini bites rolled in pistachio and cardamom. Naturally sweet.",
    image: `${BASE_URL}images/recipes/tahini_pistachio_date_bites.jpg`,
    prepTime: 15,
    servings: "24",
    difficulty: "Easy",
    cuisine: "Middle Eastern",
    course: "Dessert",
    tags: ["date balls", "tahini", "pistachio", "no-sugar-added"],
    keywords: [],
    featured: false,
    rating: 5.0,
    date_published: "2025-09-25"
  },
  {
  id: "19",
  title: "Mini Labneh & Makdouss Cups",
  slug: "mini-labneh-makdouss-cups",
  short_description: "Bite-sized cups with creamy labneh, tangy makdouss, and fresh mint.",
  image: `${BASE_URL}images/recipes/mini_labneh_makdouss_cups.jpg`,
  prepTime: 15,
  servings: "20–24 mini cups",
  difficulty: "Easy",
  cuisine: "Lebanese",
  course: "Salad & Side",
  tags: ["labneh", "makdouss", "bouchée", "mezze"],
  keywords: ["مكدوس", "لبنة"],
  featured: false,
  rating: 4.8,
  date_published: "2025-11-06"
  },
  {
    id: "20",
    title: "Smoked Salmon Sandwich on Sourdough",
    slug: "smoked-salmon-sandwich-sourdough",
    short_description: "Avocado, cottage cheese with dill, rocket leaves, smoked salmon, and red onion on sourdough.",
    image: `${BASE_URL}images/recipes/smoked_salmon_sandwich.jpg`,
    prepTime: 15,
    servings: "2",
    difficulty: "Easy",
    cuisine: "International",
    course: "Breakfast",
    tags: ["salmon", "sourdough", "avocado", "cottage-cheese", "quick"],
    keywords: ["سندويش سلمون", "خبز العجين المخمر"],
    featured: false,
    rating: 4.7,
    date_published: "2024-09-21"
  },
  {
    id: "21",
    title: "Laban Emmo",
    slug: "laban-emmo",
    short_description: "A comforting Lebanese laban dish with lamb shanks, pearl onions, and pine nuts.",
    image: `${BASE_URL}images/recipes/laban_emmo.jpg`,
    prepTime: 25,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["laban", "lamb", "comfort-food", "stew"],
    keywords: ["لبن امّو", "مرق لبن"],
    featured: false,
    rating: 4.9,
    date_published: "2024-09-16"
  },
  {
    id: "22",
    title: "Lentil Protein Crackers with Moringa",
    slug: "lentil-protein-crackers-moringa",
    short_description: "Crispy, nourishing plant-based crackers boosted with moringa.",
    image: `${BASE_URL}images/recipes/lentil_moringa_crackers.jpg`,
    prepTime: 30,
    servings: "1 large tray (10–12 servings)",
    difficulty: "Easy",
    cuisine: "Healthy",
    course: "Salad & Side",
    tags: ["lentils", "moringa", "gluten-free", "baked", "crackers"],
    keywords: ["مقرمشات العدس"],
    featured: false,
    rating: 4.6,
    date_published: "2024-09-10"
  },
  {
    id: "23",
    title: "Colorful Shrimp Stir-Fry",
    slug: "shrimp-stir-fry",
    short_description: "Juicy shrimp with peppers, zucchini, aromatics, and a quick soy-sesame sauce.",
    image: `${BASE_URL}images/recipes/shrimp_stir_fry.jpg`,
    prepTime: 15,
    servings: "4",
    difficulty: "Easy",
    cuisine: "Asian-Inspired",
    course: "Main",
    tags: ["shrimp", "stir-fry", "quick", "vegetables", "rice"],
    keywords: ["روبيان", "خضار", "قلي سريع"],
    featured: false,
    rating: 4.7,
    date_published: "2024-09-09"
  },
  {
    id: "24",
    title: "Green Bean & Lamb Stew",
    slug: "green-bean-lamb-stew",
    short_description: "Lebanese-style stewed green beans with lamb, tomato, and aromatics.",
    image: `${BASE_URL}images/recipes/green_bean_lamb_stew.jpg`,
    prepTime: 20,
    servings: "6",
    difficulty: "Medium",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["green-beans", "lamb", "stew", "tomato"],
    keywords: ["لوبيا باللحمة"],
    featured: false,
    rating: 4.6,
    date_published: "2024-09-04"
  },
  {
    id: "25",
    title: "Chard with Black-Eyed Peas (Seleq bi Loubye)",
    slug: "chard-black-eyed-peas",
    short_description: "Tender black-eyed peas, caramelized onions, and fresh lemon juice over chard.",
    image: `${BASE_URL}images/recipes/chard_black_eyed_peas.jpg`,
    prepTime: 25,
    servings: "6",
    difficulty: "Easy",
    cuisine: "Lebanese",
    course: "Main",
    tags: ["chard", "black-eyed-peas", "vegan", "comfort-food"],
    keywords: ["سلق", "لوبية"],
    featured: false,
    rating: 4.8,
    date_published: "2024-09-01"
  }

];

export async function fetchRecipesIndex(): Promise<RecipeIndexItem[]> {
  // Return data synchronously wrapped in a Promise for immediate loading
  return Promise.resolve(recipesData);
}
